// Code generated by mockery v2.35.4. DO NOT EDIT.

package mocks

import (
	dto "github.com/IrvanWijayaSardam/SelfBank/dto"
	mock "github.com/stretchr/testify/mock"
)

// mediaUpload is an autogenerated mock type for the mediaUpload type
type mediaUpload struct {
	mock.Mock
}

// FileUpload provides a mock function with given fields: file
func (_m *mediaUpload) FileUpload(file dto.File) (string, error) {
	ret := _m.Called(file)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(dto.File) (string, error)); ok {
		return rf(file)
	}
	if rf, ok := ret.Get(0).(func(dto.File) string); ok {
		r0 = rf(file)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(dto.File) error); ok {
		r1 = rf(file)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoteUpload provides a mock function with given fields: url
func (_m *mediaUpload) RemoteUpload(url dto.Url) (string, error) {
	ret := _m.Called(url)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(dto.Url) (string, error)); ok {
		return rf(url)
	}
	if rf, ok := ret.Get(0).(func(dto.Url) string); ok {
		r0 = rf(url)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(dto.Url) error); ok {
		r1 = rf(url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newMediaUpload creates a new instance of mediaUpload. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMediaUpload(t interface {
	mock.TestingT
	Cleanup(func())
}) *mediaUpload {
	mock := &mediaUpload{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
